version: "3.7"

services:
  mysql-api-template:
    container_name: mysql-api-template
    image: mysql:8.0.19
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      TZ: Europe/Madrid
    ports:
      - 3307:3306
    volumes:
      - ./mysql/data/:/var/lib/mysql/